services:
  synapse:
    image: docker.io/matrixdotorg/synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./data/synapse:/data
    depends_on:
      - synapse_db
    networks:
      - nginx_default
  synapse_db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
