services:
  lighthouseci:
    image: patrickhulce/lhci-server
    container_name: lighthouseci
    volumes:
      - ./data:/data
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
